settings:
  dropSettings:
    intoInventory: false
    onlyOwnerCanPickup: false
    visibleItemName:
      enable: true
      format: '#amount# x #eggtype#'
      coloredItemGlow: true
  dropEggsIntoInventory: false
  defaultEvents:
    - 'title:Congratulation;You found #amount# x #eggtype#'
    - 'sound:level_up;1;1.8'
    - 'command:say hi #player#'
    - 'particle:totem'
    - 'message:You just found #amount# x #eggtype# with a chance of #percentage# %'
    - 'actionbar: Found #amount# x #eggtype# with a chance of #percentage# %'
  permissionChances:
    'lightegghunter.mvp':
      increaseChanceBy: 2
    'lightegghunter.mvp++':
      increaseChanceBy: 4
  globalWorldBlacklist:
    - 'my_world'
  eggs:
    'villager':
      chance: 10
      worldBlacklist:
        - 'notInThisWorld'
      worldGuardRegionBlacklist:
        - 'worldGuardRegion'
      amount: 1
      extraEvents: []
      itemColor: GOLD
